services:
  reddit_collector:
    build: reddit_collector/
    volumes:
      - ./reddit_collector/:/app
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    ports:
      - 27017:27017

  etl:
    build: etl_job
    volumes:
      - ./etl_job/:/app
    depends_on:
      - mongodb
      - postgresdb

  postgresdb:
    image: postgres
    ports:
      - 5555:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=reddits_pgdb
  
  metabase:
    build: ./metabase/.
    volumes:
      - ./metabase/metabase-data:/metabase-data
    ports:
      - 3000:3000
    environment:
      MB_DB_FILE: /metabase-data/metabase.db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 30s
    depends_on:
      - postgresdb
